// Edit the lists below to update people, publications, news and videos.
// The first four portraits follow the order of the supplied images; verify names before public use.
const members = [
  { name: 'Adip Ranjan Das', role: 'PhD student', image: 'images/adip.png', supervisors: [{ name: 'Xianwen Kong', url: 'https://researchportal.hw.ac.uk/en/persons/xianwen-kong/' }], project: 'Adaptive dual-arm disassembly of electronic devices.' },
  { name: 'Sheena Shabana', role: 'D2AIR CDT PhD student', image: 'images/sheena.png', supervisors: [{ name: 'Marta Vallejo', url: 'https://researchportal.hw.ac.uk/en/persons/marta-vallejo/' }, { name: 'Karen Donaldson', url: 'https://www.research.ed.ac.uk/en/persons/karen-donaldson/' }], project: 'Precision robotic needle interventions in soft tissues.' },
  { name: 'Christopher Jenner', role: 'PhD student', image: 'images/christopher.png', supervisors: [{ name: 'Richard Carter', url: 'https://researchportal.hw.ac.uk/en/persons/richard-carter/' }, { name: 'Mehrdad Yaghoobi Vaighan', url: 'https://www.research.ed.ac.uk/en/persons/mehrdad-yaghoobi-vaighan/' }, { name: 'Stephen Beecher (Leonardo)' }], project: 'Dexterous manipulation for high-precision optical assembly.' },
  { name: 'David Neilan', role: 'PhD student', image: 'images/david.png', supervisors: [{ name: 'Maria', url: 'https://researchportal.hw.ac.uk/en/persons/maria-koskinopoulou/' }, { name: 'Ignacio', url: 'https://researchportal.hw.ac.uk/en/persons/ignacio-carlucho/' }, { name: 'Steven McDonagh', url: 'https://eng.ed.ac.uk/about/people/dr-steven-mcdonagh' }, { name: 'Adam Fleming (Leonardo)', url: 'https://uk.linkedin.com/in/adam-fleming-7448b4168' }], project: 'Vision-language agents for enhanced human-robot interaction in manufacturing.' },
  { name: 'Jacob Mitchell', role: 'D2AIR CDT PhD student', supervisors: [{ name: 'Frédéric Bosché (University of Edinburgh)', url: 'https://eng.ed.ac.uk/about/people/dr-frederic-bosche' }], project: 'Robotics for construction.' },
  { name: 'Prab Singh', role: 'D2AIR CDT PhD student', image: 'images/prab.png', supervisors: [{ name: 'Barbara Webb', url: 'https://homepages.inf.ed.ac.uk/bwebb/' }], project: 'Autonomous crop monitoring for UK wheat crops.' },
  { name: 'Robbie McPherson', role: 'PhD student', image: 'images/robbie-mcpherson.jpeg', project: 'Reinforcement learning for the control of aerial vehicles.' },
  { name: 'Ivalin Chobanov', role: 'PhD student', image: 'images/ivalin-chobanov.jpeg', url: 'https://ivalin.com/', supervisors: [{ name: 'Prof. Ram Ramamoorthy', url: 'https://people.inf.ed.ac.uk/Ram_Ramamoorthy.html' }], project: 'Advancing multi-agent reinforcement learning.' },
  { name: 'Ulixes Hawili', role: 'PhD student', image: 'images/ulixes-hawili.jpg', supervisors: [{ name: 'Prof. Ram Ramamoorthy', url: 'https://people.inf.ed.ac.uk/Ram_Ramamoorthy.html' }, { name: 'Prof. Yoann Altmann', url: 'https://researchportal.hw.ac.uk/en/persons/yoann-altmann/' }], project: 'Zero-shot coordination and multi-agent systems.' },
  { name: 'Favour Adetunji', role: 'PhD student', image: 'images/favour-adetunji.jpg', supervisors: [{ name: 'Maria', url: 'https://researchportal.hw.ac.uk/en/persons/maria-koskinopoulou/' }, { name: 'Ignacio', url: 'https://researchportal.hw.ac.uk/en/persons/ignacio-carlucho/' }], project: 'Pipe and cable tracking for autonomous underwater vehicles.' }
];
const papers = [
  { year: 2026, authors: 'Maria Koskinopoulou, Alperen Acemoglu, Lorenzo Civati, Leonardo S. Mattos', title: 'Cathbot-Pro: A Handheld Robotic Device for Vision-Guided Peripheral Intravenous Catheterization Using NIR Imaging', venue: 'IEEE Transactions on Medical Robotics and Bionics', doi: '10.1109/TMRB.2026.3722331', pdf: 'https://researchportal.hw.ac.uk/files/174371189/Cathbot-Pro_A_Handheld_Robotic_Device_for_Vision-Guided_Peripheral_Intravenous_Catheterization_Using_NIR_Imaging.pdf' },
  { year: 2026, authors: 'Adip Ranjan Das, Xianwen Kong, Maria Koskinopoulou', title: 'eGRAP: Graph-Based Adaptive Planning for Dual-arm Robotic Disassembly of Electronic Devices', venue: 'IEEE/ASME International Conference on Advanced Intelligent Mechatronics', doi: '10.1109/AIM65483.2026.11658063', pdf: 'https://researchportal.hw.ac.uk/files/175542002/eGRAP_Graph-Based_AAM.pdf' },
  { year: 2026, authors: 'Favour O. Adetunji, Vibhav Bharti, Maria Koskinopoulou, Yvan R. Petillot, Ignacio Carlucho', title: 'Tracking and inspection of subsea pipelines and cables using underwater vehicles: A comprehensive review', venue: 'Ocean Engineering', doi: '10.1016/j.oceaneng.2026.125884', pdf: 'https://researchportal.hw.ac.uk/files/169725467/1-s2.0-S002980182601718X-main_1_.pdf', shared: true },
  { year: 2026, authors: 'Veronica Penza, Alberto Neri, Maria Koskinopoulou, Enrico Turco, M. A. Azam, Leonardo S. Mattos', title: 'Augmented Reality Navigation in Robot-Assisted Surgery', venue: 'Handbook of Robotic and Image-Guided Surgery (Elsevier), book chapter', url: 'https://www.sciencedirect.com/science/chapter/edited-volume/abs/pii/B9780443139123000452' },
  { year: 2025, authors: 'Finny Varghese, Fernando Auat-Cheein, Maria Koskinopoulou', title: 'Finite Element Optimization of a Flexible Fin-Ray-Based Soft Robotic Gripper for Scalable Fruit Harvesting and Manipulation', venue: 'Smart Agricultural Technology', doi: '10.1016/j.atech.2025.100899', pdf: 'https://researchportal.hw.ac.uk/files/147936657/1-s2.0-S2772375525001327-main.pdf' },
  { year: 2025, authors: 'Michele Grimaldi, Patryk Cieślak, Eduardo Ochoa, Vibhav Bharti, Hayat Rajani, Ignacio Carlucho, Maria Koskinopoulou, Yvan R. Petillot, Nuno Gracias', title: 'Stonefish: Supporting Machine Learning Research in Marine Robotics', venue: 'IEEE International Conference on Robotics and Automation (ICRA)', doi: '10.1109/ICRA55743.2025.11127421', pdf: 'https://researchportal.hw.ac.uk/files/146711343/2502.11887v1.pdf', shared: true },
  { year: 2025, authors: 'F. Adetunji, A. Karukayil, P. Samant, S. Shabana, F. Varghese, U. Upadhyay, R. A. Yadav, A. Partridge, E. Pendleton, R. Plant, Y. R. Petillot, M. Koskinopoulou', title: 'Vision-based manipulation of transparent plastic bags in industrial setups', venue: 'Frontiers in Robotics and AI', doi: '10.3389/frobt.2025.1506290', pdf: 'https://researchportal.hw.ac.uk/files/146418060/frobt-12-1506290.pdf' },
  { year: 2025, authors: 'Adip Ranjan Das, Maria Koskinopoulou', title: 'Toward Sustainable Manufacturing: A Review on Innovations in Robotic Assembly and Disassembly', venue: 'IEEE Access', doi: '10.1109/ACCESS.2025.3576441', pdf: 'https://researchportal.hw.ac.uk/files/151047355/Toward_Sustainable_Manufacturing_A_Review_on_Innovations_in_Robotic_Assembly_and_Disassembly.pdf' },
  { year: 2025, authors: 'Konstantinos Kokkalis, Fotios K. Konstantinidis, Maria Koskinopoulou, Georgios Tsimiklis, Angelos Amditis, Panayiotis Frangos', title: 'MAPPS: A Multi-Agent Pick-and-Place System for Efficient Robotic Sorting', venue: 'IEEE International Conference on Imaging Systems and Techniques', doi: '10.1109/IST66504.2025.11268423' },
  { year: 2025, authors: 'Favour O. Adetunji, Vibhav Bharti, Yvan R. Petillot, Maria Koskinopoulou, Ignacio Carlucho', title: 'Towards Autonomous Subsea Longitudinal Object Detection and Tracking Using a Multi-beam Echo-Sounder', venue: 'Towards Autonomous Robotic Systems', doi: '10.1007/978-3-032-01486-3_27', pdf: 'https://researchportal.hw.ac.uk/files/160014320/Taros_paper_favour.pdf', shared: true },
  { year: 2025, authors: 'Markus Buchholz, Ignacio Carlucho, Michele Grimaldi, Maria Koskinopoulou, Yvan R. Petillot', title: 'Context-Aware Behavior Learning with Heuristic Motion Memory for Underwater Manipulation', venue: 'IEEE/RSJ International Conference on Intelligent Robots and Systems', doi: '10.1109/IROS60139.2025.11247719', pdf: 'https://researchportal.hw.ac.uk/files/163113117/2507.14099v1.pdf', shared: true },
  { year: 2025, authors: 'Diego Velásquez, Sheena Shabana, Joao Gracio Lopes, Mustafa Suphi Erden, Maria Koskinopoulou', title: 'Ultrasound-guided Robotic Aspirator for Autonomous Thoracentesis in Pleural Effusion Treatment', venue: 'IEEE International Conference on Advanced Robotics and Mechatronics', doi: '10.1109/ICARM65671.2025.11293746', pdf: 'https://researchportal.hw.ac.uk/files/149690945/ICARM25_0051_MS.pdf' },
  { year: 2024, authors: 'Roxana Azizi, Maria Koskinopoulou, Yvan Petillot', title: 'Comparison of Machine Learning Approaches for Robust and Timely Detection of PPE in Construction Sites', venue: 'Robotics', doi: '10.3390/robotics13020031', pdf: 'https://researchportal.hw.ac.uk/files/107561403/robotics-13-00031.pdf' },
  { year: 2024, authors: 'Favour O. Adetunji, Niamh Ellis, Maria Koskinopoulou, Ignacio Carlucho, Yvan R. Petillot', title: 'Digital Twins Below the Surface: Enhancing Underwater Teleoperation', venue: 'OCEANS 2024', doi: '10.1109/OCEANS51537.2024.10682270', pdf: 'https://arxiv.org/pdf/2402.07556', shared: true },
  { year: 2024, authors: 'Vibhav Bharti, Maria Koskinopoulou, Andrea Munafo, Yvan Petillot', title: 'Enhancing Image Quality Assessment Using CNN-Based Edge Detection', venue: 'OCEANS 2024', doi: '10.1109/OCEANS51537.2024.10682130' },
  { year: 2024, authors: 'Zhuoqi Cheng, Maria Koskinopoulou, Sophia Bano, Danail Stoyanov, Thiusius Rajeeth Savarimuthu, Leonardo S. Mattos', title: 'Sensing Technologies for Guidance during Needle-based Interventions', venue: 'IEEE Transactions on Instrumentation and Measurement', doi: '10.1109/TIM.2024.3441017', pdf: 'https://researchportal.hw.ac.uk/files/140267337/Sensing_Technologies_for_Guidance_during_Needle-based_Interventions.pdf' },
  { year: 2023, authors: 'Veronica Penza, Alberto Neri, Maria Koskinopoulou, Enrico Turco, Domenico Soriero, Stefano Scabini, Domenico Prattichizzo, Leonardo S. Mattos', title: 'Augmented Reality Navigation in Robot-Assisted Surgery with a Teleoperated Robotic Endoscope', venue: 'IEEE/RSJ International Conference on Intelligent Robots and Systems', doi: '10.1109/IROS55552.2023.10342282' },
  { year: 2023, authors: 'Maria Koskinopoulou, Alperen Acemoglu, Veronica Penza, Leonardo S. Mattos', title: 'Dual Robot Collaborative System for Autonomous Venous Access Based on Ultrasound and Bioimpedance Sensing Technology', venue: 'IEEE International Conference on Robotics and Automation', doi: '10.1109/ICRA48891.2023.10160848' },
  { year: 2023, authors: 'Pooyan Makvandi, Majid Shabani, Navid Rabiee, Qonita Kurnia Anjani, Aziz Maleki, Ehsan Nazarzadeh Zare, Akmal Hidayat Bin Sabri, Daniele De Pasquale, Maria Koskinopoulou, Esmaeel Sharifi, Rossella Sartorius, Mohammad Seyedhamzeh, Shayesteh Bochani, Ikue Hirata, Ana Cláudia Paiva-Santos, Leonardo S. Mattos, Ryan F. Donnelly, Virgilio Mattoli', title: 'Engineering and Development of a Tissue Model for the Evaluation of Microneedle Penetration Ability, Drug Diffusion, Photothermal Activity, and Ultrasound Imaging: A Promising Surrogate to Ex Vivo and In Vivo Tissues', venue: 'Advanced Materials', doi: '10.1002/adma.202210034', pdf: 'https://researchportal.hw.ac.uk/files/113138798/Advanced_Materials_-_2023_-_Makvandi_-_Engineering_and_Development_of_a_Tissue_Model_for_the_Evaluation_of_Microneedle.pdf' },
  { year: 2023, authors: 'Maria Koskinopoulou, Zhuoqi Cheng, Alperen Acemoglu, Darwin G. Caldwell, Leonardo S. Mattos', title: 'Robotic Devices for Assisted and Autonomous Intravenous Access', venue: 'IEEE Transactions on Medical Robotics and Bionics', doi: '10.1109/TMRB.2023.3269844', pdf: 'https://researchportal.hw.ac.uk/files/112871030/Robotic_Devices_for_Assisted_and_Autonomous_Intravenous_Access.pdf' },
  { year: 2022, authors: 'Maria Koskinopoulou, Pietro Falco, Panos Trahanias', title: 'Force-prediction Scheme for Precise Grip-lifting Movements', venue: 'IEEE International Conference on Advanced Robotics and Applications', doi: '10.1109/ICARA55094.2022.9738532' },
  { year: 2021, authors: 'Maria Koskinopoulou, Fredy Raptopoulos, George Papadopoulos, Nikitas Mavrakis, Michail Maniadakis', title: 'Robotic Waste Sorting Technology: Toward a Vision-Based Categorization System for the Industrial Robotic Separation of Recyclable Waste', venue: 'IEEE Robotics & Automation Magazine', doi: '10.1109/MRA.2021.3066040' },
  { year: 2021, authors: 'Veronica Penza, Zhuoqi Cheng, Maria Koskinopoulou, Alperen Acemoglu, Darwin G. Caldwell, Leonardo S. Mattos', title: 'Vision-Guided Autonomous Robotic Electrical Bio-Impedance Scanning System for Abnormal Tissue Detection', venue: 'IEEE Transactions on Medical Robotics and Bionics', doi: '10.1109/TMRB.2021.3098938' },
  { year: 2020, authors: 'Emmanouil Papadakis, Fredy Raptopoulos, Maria Koskinopoulou, Michail Maniadakis', title: 'On the Use of Vacuum Technology for Applied Robotic Systems', venue: 'IEEE International Conference on Mechatronics and Robotics Engineering', doi: '10.1109/ICMRE49073.2020.9065189' },
  { year: 2020, authors: 'Fredy Raptopoulos, Maria Koskinopoulou, Michail Maniadakis', title: 'Robotic Pick-and-Toss Facilitates Urban Waste Sorting', venue: 'IEEE International Conference on Automation Science and Engineering', doi: '10.1109/CASE48305.2020.9216746' },
  { year: 2020, authors: 'Maria Koskinopoulou, Michail Maniadakis, Panos Trahanias', title: 'Speed Adaptation in Learning from Demonstration through Latent Space Formulation', venue: 'Robotica', doi: '10.1017/S0263574719001449' },
  { year: 2020, authors: 'Michail Maniadakis, Emmanouil Hourdakis, Markos Sigalas, Stylianos Piperakis, Maria Koskinopoulou, Panos Trahanias', title: 'Time-Aware Multi-Agent Symbiosis', venue: 'Frontiers in Robotics and AI', doi: '10.3389/frobt.2020.503452' },
  { year: 2019, authors: 'Maria Koskinopoulou, Michail Maniadakis, Panos Trahanias', title: 'Learning spatio-temporal characteristics of human motions through observation', venue: 'Towards Autonomous Robotic Systems', doi: '10.1007/978-3-030-00232-9_9' },
  { year: 2018, authors: 'Stylianos Piperakis, Maria Koskinopoulou, Panos Trahanias', title: 'Nonlinear State Estimation for Humanoid Robot Walking', venue: 'IEEE Robotics and Automation Letters', doi: '10.1109/LRA.2018.2852788' },
  { year: 2016, authors: 'Maria Koskinopoulou, Panos Trahanias', title: 'A methodological framework for robotic reproduction of observed human actions: Formulation using latent space representation', venue: 'IEEE-RAS International Conference on Humanoid Robots', doi: '10.1109/HUMANOIDS.2016.7803331' },
  { year: 2016, authors: 'Maria Koskinopoulou, Stylianos Piperakis, Panos Trahanias', title: 'Learning from demonstration facilitates human-robot collaborative task execution', venue: 'ACM/IEEE International Conference on Human-Robot Interaction', doi: '10.1109/HRI.2016.7451734' }
];
const news = [
  { date: '2026', title: 'Royal Society Research Grant (£30,000) awarded for “Perception and Sensor Fusion for Robotic Needle Steering in Deformable Environments”; project starts 1 October 2026', url: 'https://hw-rmas.worktribe.com/record.jx?recordid=1881893', linkLabel: 'Grant' },
  { date: 'Aug 2026', title: 'eGRAP published at IEEE/ASME AIM 2026', url: 'https://doi.org/10.1109/AIM65483.2026.11658063', linkLabel: 'Paper' },
  { date: 'Aug 2026', title: 'Cathbot-Pro published in IEEE Transactions on Medical Robotics and Bionics', url: 'https://doi.org/10.1109/TMRB.2026.3722331', linkLabel: 'Paper' },
  { date: 'Jun 2026', title: 'Maria joins Robot Talk for Episode 159: “Robot sensing and manipulation”', url: 'https://www.robottalk.org/2026/06/05/episode-159-maria-koskinopoulou/', video: 'https://www.youtube.com/watch?v=fimNuQGfcLE', linkLabel: 'Podcast' },
  { date: 'May 2024', title: 'Maria is named as a co-inventor on patent WO2024089289A1, a catheterization device with automatic needle insertion and rotation', url: 'https://patents.google.com/patent/WO2024089289A1/en', linkLabel: 'Patent' },
  { date: '2022', title: 'Best Presentation Award, IEEE ICARA 2022' },
  { date: '2018–19', title: 'PhD research scholarship at ABB Corporate Research, Sweden', url: 'https://sites.google.com/view/mariakoskinopoulou/research', linkLabel: 'Background' },
  { date: '2017–19', title: 'Hellenic Foundation for Research and Innovation (HFRI) PhD Fellowship', url: 'https://sites.google.com/view/mariakoskinopoulou/research', linkLabel: 'Background' },
  { date: '2016', title: 'IEEE-RAS Humanoids travel award' }
];
const additionalHonours = [
  'Robotics: Science and Systems (RSS) Women in Robotics student award'
];
const videos = [
  { title: 'AIM research video', label: 'AIM', id: 'pO8HsUYfkjA' },
  { title: 'RA-L research video', label: 'IEEE Robotics and Automation Letters', id: 'lEE3qmOJsXo' }
];
