const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl = s => /^https:\/\//.test(s) ? s : '#';
document.querySelector('#year').textContent = new Date().getFullYear();
if(document.querySelector('#member-list')) document.querySelector('#member-list').innerHTML = members.map(m => `<article class="member">${m.image ? `<img class="portrait" src="${esc(m.image)}" alt="Portrait of ${esc(m.name)}" loading="lazy">` : `<div class="portrait initials" aria-hidden="true">${esc(m.name.split(' ').map(x=>x[0]).join(''))}</div>`}<div><h4>${esc(m.name)}</h4><p>${esc(m.role)}</p></div></article>`).join('');
if(document.querySelector('#news-list')) document.querySelector('#news-list').innerHTML = news.map(n => `<div class="news-item"><time>${esc(n.date)}</time><p><a href="${esc(safeUrl(n.url))}" target="_blank" rel="noopener">${esc(n.title)} ↗</a></p></div>`).join('');
if(document.querySelector('#paper-list')) document.querySelector('#paper-list').innerHTML = papers.map(p => `<article class="paper"><span class="paper-year">${esc(p.year)}</span><div><h3><a href="${esc(safeUrl(p.url))}" target="_blank" rel="noopener">${esc(p.title)} ↗</a></h3><p>${esc(p.venue)}</p></div></article>`).join('');
if(document.querySelector('#video-list')) document.querySelector('#video-list').innerHTML = videos.map(v => `<a class="video-item" href="${esc(safeUrl(v.url))}" target="_blank" rel="noopener"><small>${esc(v.label)}</small><h3>${esc(v.title)} ↗</h3></a>`).join('');
const toggle = document.querySelector('.menu-toggle'), nav = document.querySelector('nav');
toggle.addEventListener('click', () => {const open = nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close menu':'Open menu')});
nav.querySelectorAll('a').forEach(a => a.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));
